=== EliasKotlyar/EasyTemplate/etc/easytemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="config" type="configType"/>

  <xs:complexType name="paramType">
    <xs:sequence>
      <xs:element type="xs:string" minOccurs="1" maxOccurs="1" name="value"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="translate" use="optional"/>
  </xs:complexType>

  <xs:complexType name="inputType">
    <xs:sequence>
      <xs:element type="xs:string" name="comment" minOccurs="0"/>
      <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute type="xs:boolean" name="required" use="optional"/>
  </xs:complexType>

  <xs:complexType name="frontendType">
    <xs:sequence>
      <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="renderer" use="optional"/>
  </xs:complexType>

  <xs:complexType name="backendType">
    <xs:sequence>
      <xs:element type="xs:string" name="label"/>
      <xs:element type="xs:string" name="comment" minOccurs="0"/>
      <xs:element type="inputType" name="input"/>
    </xs:sequence>
    <xs:attribute type="xs:integer" name="sort" use="optional"/>
    <xs:attribute type="xs:string" name="translate" use="optional"/>
  </xs:complexType>

  <xs:complexType name="templateType">
    <xs:sequence>
      <xs:element type="xs:string" name="label"/>
      <xs:element type="xs:string" name="comment" minOccurs="0"/>
      <xs:element type="xs:string" name="image" minOccurs="0"/>
      <xs:element type="fieldsType" name="fields"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="code" use="required"/>
    <xs:attribute type="xs:string" name="template" use="required"/>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute type="xs:string" name="translate" use="optional" default="label"/>
    <xs:attribute type="xs:string" name="enabled" use="required" default="1"/>
    <xs:attribute type="xs:string" name="sort" use="optional"/>

    <xs:attribute type="xs:string" name="min_sizex" use="optional"/>
    <xs:attribute type="xs:string" name="min_sizey" use="optional"/>
    <xs:attribute type="xs:string" name="max_sizex" use="optional"/>
    <xs:attribute type="xs:string" name="max_sizey" use="optional"/>
  </xs:complexType>
  <xs:complexType name="groupType">
    <xs:sequence>
      <xs:element type="xs:string" name="label"/>
      <xs:element type="templatesType" name="templates"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="code" use="required"/>
    <xs:attribute type="xs:string" name="translate" use="optional" default="label"/>
    <xs:attribute type="xs:string" name="enabled" use="required" default="1"/>
  </xs:complexType>
  <xs:complexType name="templatesType">
    <xs:sequence>
      <xs:element type="templateType" name="template" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="easytemplateType">
    <xs:sequence>
      <xs:element type="groupType" name="group" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="configType">
    <xs:sequence>
      <xs:element type="easytemplateType" name="easytemplate"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fieldType">
    <xs:sequence>
      <xs:element type="backendType" name="backend" maxOccurs="1" minOccurs="0"/>
      <xs:element type="frontendType" name="frontend" maxOccurs="1" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="code" use="required"/>
    <xs:attribute type="xs:string" name="model" use="required"/>
    <xs:attribute type="xs:string" name="required" use="optional" default="1"/>
  </xs:complexType>
  <xs:complexType name="fieldsType">
    <xs:sequence>
      <xs:element type="fieldType" name="field" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== EliasKotlyar/EasyTemplate/Test/Model/Config/Reader/_files/easytemplate.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Webguys_Easytemplate:etc/easytemplate.xsd">
    <easytemplate>

        <group code="test" translate="label" enabled="1">
            <label>Test Templates</label>
            <templates>

                <template code="testtemplate"
                          template="easytemplate/template/testtemplate.phtml"
                          type="easytemplate/template"
                          translate="label,comment"
                          enabled="1"
                          sort="1"
                          min_sizey="1"
                          min_sizex="1"
                          max_sizex="1"
                          max_sizey="12"
                        >
                    <label>Test Text template</label>
                    <comment>A test template</comment>
                    <fields>

                        <field code="field1" model="easytemplate/template_data_varchar">

                            <backend sort="1" translate="label,comment">
                                <label>Text 1</label>
                                <comment>Comment 1</comment>
                                <input type="text" required="0"/>
                            </backend>

                        </field>

                        <field code="field2" model="easytemplate/template_data_varchar">

                            <backend sort="10" translate="label,comment">
                                <label>Text 2</label>
                                <comment>Comment 2</comment>
                                <input type="text" required="0"/>
                            </backend>

                        </field>

                    </fields>
                </template>

                <template code="imagetest"
                          template="path/to/template.phtml"
                          enabled="1"
                          type="easytemplate/template"
                          sort="10"
                        >
                    <label>Test</label>
                    <comment>Bla Blub</comment>
                    <fields>
                        <field code="image_test" model="easytemplate/template_data_varchar">

                            <backend sort="5" translate="label,comment">
                                <label>Magento Media Gallery</label>
                                <comment>Comment for image-input</comment>
                                <input type="select" required="0">
                                    <param name="abc" translate="value">
                                        <value>test</value>
                                    </param>
                                </input>
                            </backend>

                            <frontend renderer="easytemplate/renderer_image">
                                <param name="blub">
                                    <value>test</value>
                                </param>
                            </frontend>

                        </field>
                    </fields>
                </template>

            </templates>
        </group>
    </easytemplate>
</config>
